### ISSUE TITLE
Reporte_De_Practica_De_Control_Para_Cajas

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Abraham890#2]
[Abraham_Reyes_Ortiz_Reporte _De_Caja_De_Texto_Personalizado_4US.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Abraham890/files/6347413/Abraham_Reyes_Ortiz_Reporte._De_Caja_De_Texto_Personalizado_4US.pdf)

**Comment by Aricel117** [comment]
Excelente Trabajo Tiene 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
